#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.Email.Template.Management.Frontend.Views.EmailTemplateManagement.Mobile
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Script.Serialization;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmailTemplateManagement/Mobile/Delete.cshtml")]
    public class Delete : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Delete()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div id=\"delete\" data-role=\"page\">\r\n \r\n  <div data-role=\"header\">\r\n    <h1>Delete" +
"</h1>\r\n  </div>\r\n \r\n  <div data-role=\"content\">\r\n    <div id=\"delete-template-co" +
"ntainer\">\r\n        <p>Are you sure you wish to delete this item?</p> \r\n        <" +
"a href=\"#\" data-bind=\"click: function() { email_template_delete.raiseBack() }\" c" +
"lass=\"ui-block-a\" data-role=\"button\" data-icon=\"arrow-l\" data-theme=\"a\" data-inl" +
"ine=\"true\">Back</a>\r\n        <a href=\"#\" class=\"ui-block-b\" data-role=\"button\" d" +
"ata-icon=\"delete\" data-theme=\"b\" data-inline=\"true\">Delete</a>\r\n    </div>\r\n  </" +
"div>\r\n \r\n  <div data-role=\"footer\">\r\n    <h4>Designed and built by <a href=\"http" +
"://www.threebytes.co.uk\" target=\"_blank\">Three Bytes</a>.</h4>\r\n  </div>\r\n</div>" +
"\r\n\r\n<script type=\"text/javascript\">\r\n\r\n    var email_template_delete = {};\r\n\r\n  " +
"  (function (index) {\r\n\r\n        email_template_delete = index;\r\n\r\n        index" +
".Id = ko.observable();\r\n        index.Name = ko.observable();\r\n\r\n        index.r" +
"aiseBack = function () {\r\n            jQuery(document).trigger(\'emailTemplateDet" +
"ails\', [index]);\r\n        };\r\n\r\n        jQuery(document).bind(\'emailTemplateDele" +
"te\', function (event, id) {\r\n\r\n            jQuery.getJSON(\"Template/Delete/\" + i" +
"d, function (data) {\r\n\r\n                index.Id(data.Id);\r\n                inde" +
"x.Name(data.Name);\r\n\r\n                jQuery.mobile.changePage(\"#delete\", \"flip\"" +
", true, false);\r\n            });\r\n        });\r\n\r\n        jQuery(function () {\r\n " +
"           ko.applyBindings(index, jQuery(\'#delete-template-container\')[0]);\r\n  " +
"      });\r\n    } (email_template_delete));\r\n</script>");


        }
    }
}
#pragma warning restore 1591
