#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.Email.Template.Management.Frontend.Views.EmailTemplateManagement.Mobile
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Script.Serialization;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmailTemplateManagement/Mobile/Edit.cshtml")]
    public class Edit : System.Web.Mvc.WebViewPage<ThreeBytes.Email.Template.Management.Entities.EmailTemplateManagementTemplate>
    {
        public Edit()
        {
        }
        public override void Execute()
        {

WriteLiteral("           \r\n<div id=\"edit\" data-role=\"page\">\r\n    <div data-role=\"header\">\r\n    " +
"    <h1>Edit</h1>\r\n    </div>\r\n    <div data-role=\"content\">\r\n        <div id=\"e" +
"dit-template-container\">\r\n            ");


            
            #line 9 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
       Write(Html.HiddenFor(model => model.Id, new { @data_bind = "value: Id" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n            <div data-role=\"fieldcontain\">\r\n                ");


            
            #line 12 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.LabelFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 13 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.TextBoxFor(model => model.Name, new { @data_bind = "value: Name" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 14 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <button type=\"submit\" data-bind=\"click: function() { email_temp" +
"late_edit.saveName() }\" class=\"btn primary\" data-theme=\"b\">Rename</button>\r\n    " +
"        </div>\r\n            <div data-role=\"fieldcontain\">\r\n                ");


            
            #line 18 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.LabelFor(model => model.From));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 19 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.TextBoxFor(model => model.From, new { @data_bind = "value: From" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 20 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.From));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <button type=\"submit\" data-bind=\"click: function() { email_temp" +
"late_edit.saveFromAddress() }\" class=\"btn primary\" data-theme=\"b\">Rename</button" +
">\r\n            </div>\r\n            <div data-role=\"fieldcontain\">\r\n             " +
"   ");


            
            #line 24 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.LabelFor(model => model.Subject));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 25 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.TextBoxFor(model => model.Subject, new { @data_bind = "value: Subject" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 26 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Subject));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div data-role=\"fieldcontain\">\r\n               " +
" ");


            
            #line 29 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.LabelFor(model => model.Body));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 30 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.TextAreaFor(model => model.Body, new { @data_bind = "value: Body" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 31 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Body));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div data-role=\"fieldcontain\">\r\n               " +
" ");


            
            #line 34 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.LabelFor(model => model.IsHtml));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 35 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.CheckBoxFor(model => model.IsHtml, new { @data_bind = "value: IsHtml" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 36 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div data-role=\"fieldcontain\">\r\n               " +
" ");


            
            #line 39 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.LabelFor(model => model.Encoding));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 40 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.EnumDropDownListFor(model => model.Encoding));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 41 "..\..\Views\EmailTemplateManagement\Mobile\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Encoding));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <button type=\"submit\" data-bind=\"click: function() { email_temp" +
"late_edit.saveTemplateContent() }\" class=\"btn primary\" data-theme=\"b\">Update</bu" +
"tton>\r\n            </div>\r\n            <a href=\"#\" data-bind=\"click: function() " +
"{ email_template_edit.raiseBack() }\" data-role=\"button\" data-icon=\"arrow-l\" data" +
"-theme=\"a\">Back</a>\r\n        </div>\r\n    </div>\r\n    <div data-role=\"footer\">\r\n " +
"       <h4>Designed and built by <a href=\"http://www.threebytes.co.uk\" target=\"_" +
"blank\">Three Bytes</a>.</h4>\r\n    </div>\r\n</div>\r\n\r\n<script type=\"text/javascrip" +
"t\">\r\n\r\n    var email_template_edit = {};\r\n\r\n    (function (index) {\r\n\r\n        e" +
"mail_template_edit = index;\r\n\r\n        index.Id = ko.observable();\r\n\r\n        in" +
"dex.Name = ko.observable();\r\n        index.ApplicationName = ko.observable();\r\n " +
"       index.From = ko.observable();\r\n        index.Subject = ko.observable();\r\n" +
"        index.Body = ko.observable();\r\n        index.IsHtml = ko.observable();\r\n" +
"        index.Encoding = ko.observable();\r\n\r\n        index.raiseBack = function " +
"() {\r\n            jQuery(document).trigger(\'emailTemplateDetails\', [index]);\r\n  " +
"      };\r\n\r\n        index.saveName = function (form) {\r\n            var data = j" +
"Query(form).serialize();\r\n\r\n            jQuery.post(\"Template/Rename\", data, fun" +
"ction (returnedData) {\r\n                jQuery(document).trigger(\'emailTemplateU" +
"pdated\', [returnedData.Id]);\r\n            });\r\n        };\r\n\r\n        index.saveF" +
"romAddress = function (form) {\r\n            var data = jQuery(form).serialize();" +
"\r\n\r\n            jQuery.post(\"Template/RenameFromAddress\", data, function (return" +
"edData) {\r\n                jQuery(document).trigger(\'emailTemplateUpdated\', [ret" +
"urnedData.Id]);\r\n            });\r\n        };\r\n\r\n        index.saveTemplateConten" +
"t = function (form) {\r\n            var data = jQuery(form).serialize();\r\n\r\n     " +
"       jQuery.post(\"Template/Update\", data, function (returnedData) {\r\n         " +
"       jQuery(document).trigger(\'emailTemplateUpdated\', [returnedData.Id]);\r\n   " +
"         });\r\n        };\r\n\r\n        jQuery(document).bind(\'emailTemplateEdit\', f" +
"unction (event, id) {\r\n\r\n            jQuery.getJSON(\"Template/Edit/\" + id, funct" +
"ion (data) {\r\n\r\n                index.Id(data.Id);\r\n                index.Name(d" +
"ata.Name);\r\n                index.ApplicationName(data.ApplicationName);\r\n      " +
"          index.From(data.From);\r\n                index.Subject(data.Subject);\r\n" +
"                index.Body(data.Body);\r\n                index.IsHtml(data.IsHtml" +
");\r\n                index.Encoding(data.Encoding);\r\n\r\n                jQuery.mob" +
"ile.changePage(\"#edit\", \"flip\", true, false);\r\n            });\r\n        });\r\n\r\n " +
"       jQuery(function () {\r\n            ko.applyBindings(index, jQuery(\'#edit-t" +
"emplate-container\')[0]);\r\n        });\r\n    } (email_template_edit));\r\n</script>");


        }
    }
}
#pragma warning restore 1591
