#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.User.Dashboard.NewestUsers.Frontend.Views.NewestUsers
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Script.Serialization;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Data.ResultSets.Abstract;
    using ThreeBytes.Core.Extensions.Mvc;
    using ThreeBytes.User.Dashboard.NewestUsers.Entities;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/NewestUsers/MostRecent.cshtml")]
    public class MostRecent : System.Web.Mvc.WebViewPage<IPagedResult<DashboardNewestUsers>>
    {
        public MostRecent()
        {
        }
        public override void Execute()
        {

WriteLiteral(@"
<div id=""newest-users-container"">
    <div data-bind=""pagedGrid: pagedViewModel, pagedGridTemplate: 'newest-users-table-tmpl', pagedGridPagerTemplate: 'ko_simpleGrid_basicPageLinks'""></div>
</div>

<script type=""text/x-jquery-tmpl"" id=""newest-users-table-tmpl"">
    <div class=""widget widget-table"">
        <div class=""widget-header"">
            <span class=""icon-file""></span>
            <h3>Newest Users</h3>
        </div>
        <div class=""widget-content"">
            <table id=""newest-users-table"" class=""table table-striped table-bordered table-condensed"">
                <thead>
                    <tr>
                        <th class=""header"">
                            Username
                        </th>
                        <th class=""header"">
                            Registered
                        </th>
                    </tr>
                </thead>
                <tbody id=""newest-users-tbody"" data-bind=""foreach: items"">
                    <tr>        
                        <td data-bind=""text: Username""></td>
                        <td data-bind=""text: RegistrationDateTime""></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</script>

");


            
            #line 36 "..\..\Views\NewestUsers\MostRecent.cshtml"
   
    using (Html.BeginScriptContext())
    {
        Html.AddScriptBlock(@"
        var newest_users_model  = {};

        (function (index) {

            var itemMapping = {
                'RegistrationDateTime': ko.utils.getTimeAgoFromJson(),
			    'CreationDateTime': ko.utils.getDateFromJson(),
                'LastModifiedDateTime': ko.utils.getDateFromJson()
		    };

            var itemViewModel = function(data) {
			    ko.mapping.fromJS(data, itemMapping, this);
		    };

            var mapping = {	
			    'Items': {
				    create: function(options) {
					    return new itemViewModel(options.data);
				    }
			    }
		    };

            newest_users_model = index = ko.mapping.fromJS(" + @Html.Raw(new JavaScriptSerializer().Serialize(Model)) + @", mapping);

            index.pagedViewModel = new ko.pagedGrid.viewModel({
                controller: 'NewestUsers',
                action: 'GetPage',
                data: index,
                singular: 'User',
                plural: 'Users',
                loadPageCallback: function(data) {
                    ko.mapping.fromJS(data, index);
                },
                columns: [
                    { headerText: 'Username', rowText: 'Name' },
                    { headerText: 'Registration', rowText: 'RegistrationDateTime' }
                ]
            });
        
            jQuery(function() {
                ko.applyBindings(index, jQuery('#newest-users-container')[0]);
            });

        } (newest_users_model));");
    }


            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
