#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.ProjectHollywood.History.Frontend.Views.History
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/History/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\History\Index.cshtml"
  
    Page.Title = "History";


            
            #line default
            #line hidden
WriteLiteral(@"<section id=""history"">
    <div class=""row"">
        <div class=""span6"">
            <div id=""about-us-carousel"" class=""carousel slide"">
                <div class=""carousel-inner"">
                    <div class=""item active"">
                    <img src=""");


            
            #line 10 "..\..\Views\History\Index.cshtml"
                         Write(Url.Content("~/img/bootstrap-mdo-sfmoma-01.jpg"));

            
            #line default
            #line hidden
WriteLiteral(@""" alt="""">
                    <div class=""carousel-caption"">
                        <h4>First Thumbnail label</h4>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    </div>
                    </div>
                    <div class=""item"">
                    <img src=""");


            
            #line 17 "..\..\Views\History\Index.cshtml"
                         Write(Url.Content("~/img/bootstrap-mdo-sfmoma-02.jpg"));

            
            #line default
            #line hidden
WriteLiteral(@""" alt="""">
                    <div class=""carousel-caption"">
                        <h4>Second Thumbnail label</h4>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    </div>
                    </div>
                    <div class=""item"">
                    <img src=""");


            
            #line 24 "..\..\Views\History\Index.cshtml"
                         Write(Url.Content("~/img/bootstrap-mdo-sfmoma-03.jpg"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"\">\r\n                    <div class=\"carousel-caption\">\r\n                  " +
"      <h4>Third Thumbnail label</h4>\r\n                        <p>Cras justo odio" +
", dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida" +
" at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>\r\n    " +
"                </div>\r\n                    </div>\r\n                </div>\r\n    " +
"            <a class=\"left carousel-control\" href=\"#about-us-carousel\" data-slid" +
"e=\"prev\">‹</a>\r\n                <a class=\"right carousel-control\" href=\"#about-u" +
"s-carousel\" data-slide=\"next\">›</a>\r\n            </div>\r\n        </div>\r\n       " +
" <div class=\"span6\"> \r\n            <div class=\"widget\">\r\n                <div cl" +
"ass=\"widget-header\">\r\n                    <i class=\"icon-pushpin\"></i>\r\n        " +
"            <h3>Our History</h3>\r\n                </div>\r\n                <div c" +
"lass=\"widget-content\">\r\n                    <p>The global de Wolfe dynasty histo" +
"rically and still today, has its members at the forefront of the entertainment, " +
"<a href=\"http://www.dewolfe.co.uk/\" rel=\'tooltip\' title=\'For more information on" +
" de Wolfe Music click.\'>music*</a>, and legal industries.</p>\r\n                 " +
"   <p>\r\n                        The late Felix de Wolfe, was the founder of the " +
"Felix de Wolfe Theatrical and Literary Agency, which for over sixty years has re" +
"presented some of the best loved internationally renowned stars.\r\n              " +
"          His daughter Caroline de Wolfe, who took the helm in 2004, worked alon" +
"gside him for 20 years and shares his passion for the business and his tradition" +
"al work ethic.\r\n                    </p>\r\n                    <p>\r\n             " +
"           Felix\'s hallmarks as an agent were his talent for friendship and his " +
"endless courtesy and patience. Many of his clients became personal friends, and " +
"his reputation throughout the industry was a fair but charmingly  effective nego" +
"tiator.\r\n                        In a world where celebrity has become the unive" +
"rsal currency, Felix\'s style was wonderfully un-vulgar and full or old-world gra" +
"vitas.\r\n                        He simply wouldn\'t countenance short-term money-" +
"spinning deals.\r\n                        Client\'s careers were, in many cases li" +
"terally, a lifetime\'s reponsibility.\r\n                    </p>\r\n                " +
"    <p>\r\n                        His solicitude and professional charm cloaked a" +
" brilliant instinct for matching talent to popular taste: few agents were able t" +
"o read the emerging zeitgeist like de Wolfe.\r\n                        These rare" +
" qualities are still the corner stones of the agency ethos today.\r\n             " +
"       </p>\r\n                    <p>\r\n                        Through Caroline a" +
"nd her team\'s progressive approach she has successfully renewed the agency witho" +
"ut compromising her father\'s principles, pushing it forward into a new and deman" +
"ding present.\r\n                        Developing and strengthening home and int" +
"ernational relationships, to be a catalyst for the careers of her lesser-known c" +
"lients, and a facilitator to the already established ones.\r\n                    " +
"</p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</" +
"section>");


        }
    }
}
#pragma warning restore 1591
