#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.Logging.Host.Home.Frontend.Views.LoggingHost
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    using ThreeBytes.Logging.Host.Home.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/LoggingHost/About.cshtml")]
    public class About : System.Web.Mvc.WebViewPage<dynamic>
    {
        public About()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\LoggingHost\About.cshtml"
  
    Page.Title = Resources.BrowserTitleAbout;


            
            #line default
            #line hidden
WriteLiteral("\r\n<section id=\"about\">\r\n    <div class=\"page-header\"> \r\n        <h1>");


            
            #line 7 "..\..\Views\LoggingHost\About.cshtml"
       Write(Resources.AboutThreeBytesLogging);

            
            #line default
            #line hidden
WriteLiteral("</h1> \r\n    </div>\r\n    <div class=\"row\">\r\n        <div class=\"span16 columns\">\r\n" +
"        </div>            \r\n    </div>\r\n</section>\r\n");


        }
    }
}
#pragma warning restore 1591
