#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.User.Dashboard.Host.Frontend.Views.UserDashboardHost
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/UserDashboardHost/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\UserDashboardHost\Index.cshtml"
  
    ViewBag.Title = "User Dashboard";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"main\">\t\r\n    <div class=\"main-inner\">\r\n        <div class=\"containe" +
"r\">\r\n            <section id=\"user-user-home\">\r\n                <div class=\"row\"" +
">    \r\n\t      \t        <div class=\"span12\">      \t\t\r\n\t      \t\t        <div class" +
"=\"widget big-stats-container\">\t\t\r\n\t      \t\t\t        <div class=\"widget-content\">" +
"\t\t\t\r\n\t\t\t      \t\t        <div id=\"big_stats\" class=\"cf\">\r\n\t\t\t\t\t\t\t        <div cla" +
"ss=\"stat\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t        <h4>Logins Today</h4>\r\n\t\t\t\t\t\t\t\t        <span" +
" class=\"value\">12</span>\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t        </div>\t\t\t\t\r\n\t\t\t\t\t\t\t        <div" +
" class=\"stat\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t        <h4>Registrations Today</h4>\r\n\t\t\t\t\t\t\t\t  " +
"      <span class=\"value\">23</span>\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t        </div>\r\n\t\t\t\t\t\t\t     " +
"   <div class=\"stat\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t        <h4>Returned Items Today</h4>\r\n\t\t" +
"\t\t\t\t\t\t        <span class=\"value\">2</span>\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t        </div>\r\n\t\t\t\t\t" +
"\t\t        <div class=\"stat\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t        <h4>Something Else</h4>\r\n\t" +
"\t\t\t\t\t\t\t        <span class=\"value\">13</span>\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t        </div>\r\n\t\t\t" +
"\t\t\t        </div>\t\t\t\t\r\n\t\t\t\t\t        </div>\t\t\t\t\t\r\n\t\t\t\t        </div>\r\n\t      \t   " +
"     </div>\t      \t\r\n\t  \t        </div>\r\n                <div class=\"row\">\r\n    " +
"                <div class=\"span8\">            \r\n                        <div cl" +
"ass=\"widget\">\r\n                            <div class=\"widget-header\">\r\n        " +
"                        <i class=\"icon-star\"></i>\r\n                             " +
"   <h3>Login Statistics</h3>\r\n                            </div>\r\n              " +
"              <div class=\"widget-content\">\r\n                                <div" +
" class=\"row\">    \r\n                                    <div class=\"span3\">\r\n");


            
            #line 45 "..\..\Views\UserDashboardHost\Index.cshtml"
                                           Html.RenderAction("DailyStatistics", "LoginStatisticsDaily"); 

            
            #line default
            #line hidden

            
            #line 46 "..\..\Views\UserDashboardHost\Index.cshtml"
                                           Html.RenderAction("MonthlyStatistics", "LoginStatisticsMonthly"); 

            
            #line default
            #line hidden
WriteLiteral("                                    </div>\r\n                                    <" +
"div class=\"span4\">\r\n");


            
            #line 49 "..\..\Views\UserDashboardHost\Index.cshtml"
                                           Html.RenderAction("QuarterlyStatistics", "LoginStatisticsQuarterly"); 

            
            #line default
            #line hidden

            
            #line 50 "..\..\Views\UserDashboardHost\Index.cshtml"
                                           Html.RenderAction("YearlyStatistics", "LoginStatisticsYearly"); 

            
            #line default
            #line hidden
WriteLiteral(@"                                    </div>  
                                </div>
                            </div>
                        </div>
                        <div class=""widget"">
                            <div class=""widget-header"">
                                <i class=""icon-star""></i>
                                <h3>Registration Statistics</h3>
                            </div>
					
                            <div class=""widget-content"">
                                <div class=""row""> 
                                    <div class=""span3"">
");


            
            #line 64 "..\..\Views\UserDashboardHost\Index.cshtml"
                                           Html.RenderAction("DailyStatistics", "RegistrationStatisticsDaily"); 

            
            #line default
            #line hidden

            
            #line 65 "..\..\Views\UserDashboardHost\Index.cshtml"
                                           Html.RenderAction("MonthlyStatistics", "RegistrationStatisticsMonthly"); 

            
            #line default
            #line hidden
WriteLiteral("                                    </div>\r\n                                    <" +
"div class=\"span4\">\r\n");


            
            #line 68 "..\..\Views\UserDashboardHost\Index.cshtml"
                                           Html.RenderAction("QuarterlyStatistics", "RegistrationStatisticsQuarterly"); 

            
            #line default
            #line hidden

            
            #line 69 "..\..\Views\UserDashboardHost\Index.cshtml"
                                           Html.RenderAction("YearlyStatistics", "RegistrationStatisticsYearly"); 

            
            #line default
            #line hidden
WriteLiteral("                                    </div>\r\n                                </div" +
">\r\n                            </div>\r\n                        </div>\r\n         " +
"           </div>\r\n                    <div class=\"span4\">\r\n");


            
            #line 76 "..\..\Views\UserDashboardHost\Index.cshtml"
                           Html.RenderAction("MostLoggedIn", "ActiveUsers"); 

            
            #line default
            #line hidden

            
            #line 77 "..\..\Views\UserDashboardHost\Index.cshtml"
                           Html.RenderAction("MostRecent", "NewestUsers"); 

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n            </section>\r\n     " +
"   </div>\r\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
