CREATE TABLE [dbo].[ThespianViewThespians] (
    [ThespianId]						UNIQUEIDENTIFIER NOT NULL,
    [ItemId]							UNIQUEIDENTIFIER NOT NULL,
    [FirstName]							NVARCHAR (35)    NOT NULL,
    [LastName]							NVARCHAR (35)    NOT NULL,
	[ProfileImageLocation]				NVARCHAR (100)   NULL,
    [ProfileThumbnailImageLocation]		NVARCHAR (100)   NULL,
	[DateOfBirth]						DATETIME         NULL,
    [Gender]							NVARCHAR (6)     NOT NULL,
	[Email]								NVARCHAR (320)   NULL,
	[Location]							NVARCHAR (200)   NULL,
    [Height]							INT				 NULL,
	[Weight]							INT				 NULL,
    [PlayingAge]						INT				 NULL,
	[EyeColour]							NVARCHAR (20)    NULL,
    [HairLength]						NVARCHAR (20)    NULL,
	[Summary]							NVARCHAR (MAX)   NULL,
    [Twitter]							NVARCHAR (20)    NULL,
	[Facebook]							NVARCHAR (255)   NULL,
    [Spotlight]							NVARCHAR (255)   NULL,
	[Imdb]								NVARCHAR (255)   NULL,
	[ThespianType]						NVARCHAR (14)    NOT NULL,
	[CreatedBy]							NVARCHAR (35)    NOT NULL,  
    [LastModifiedBy]					NVARCHAR (35)    NULL,
    [CreationDateTime]					DATETIME         NOT NULL,
    [LastModifiedDateTime]				DATETIME         NULL,
    [Operation]							NVARCHAR (MAX)   NULL
);

