ALTER TABLE [dbo].[NewsViewNewsArticles]
    ADD CONSTRAINT [PK_NewsViewNewsArticles] PRIMARY KEY CLUSTERED ([NewsArticleId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

