ALTER TABLE [dbo].[NewsListNewsArticles]
    ADD CONSTRAINT [PK_NewsListNewsArticles] PRIMARY KEY CLUSTERED ([NewsArticleId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

