ALTER TABLE [dbo].[TeamManagementEmployees]
    ADD CONSTRAINT [PK_TeamManagementEmployees] PRIMARY KEY CLUSTERED ([EmployeeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

