ALTER TABLE [dbo].[TeamViewEmployees]
    ADD CONSTRAINT [PK_TeamViewEmployees] PRIMARY KEY CLUSTERED ([EmployeeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

