#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.User.Host.Home.Frontend.Views.Error
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    using ThreeBytes.User.Host.Home.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Error/Roles.cshtml")]
    public class Roles : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Roles()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Error\Roles.cshtml"
  
    ViewBag.Title = Resources.BrowserTitleErrorRole;


            
            #line default
            #line hidden
WriteLiteral("\r\n<section id=\"authorisation-role-error\">\r\n    <div class=\"hero-unit\"> \r\n        " +
"<h1>");


            
            #line 7 "..\..\Views\Error\Roles.cshtml"
       Write(Resources.ThreeBytesUser);

            
            #line default
            #line hidden
WriteLiteral("</h1> \r\n    </div>\r\n    <div class=\"row\">\r\n        ");


            
            #line 10 "..\..\Views\Error\Roles.cshtml"
   Write(Resources.DoNotHaveSecurityRoles);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</section>");


        }
    }
}
#pragma warning restore 1591
