#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.Email.Template.Management.Frontend.Views.EmailTemplateManagement
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Script.Serialization;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    using ThreeBytes.Email.Template.Management.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmailTemplateManagement/Edit.cshtml")]
    public class Edit : System.Web.Mvc.WebViewPage<ThreeBytes.Email.Template.Management.Entities.EmailTemplateManagementTemplate>
    {
        public Edit()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
  
    ViewBag.Title = Resources.BrowserTitleEdit;


            
            #line default
            #line hidden
WriteLiteral("\r\n<div id=\"edit-template-container\">\r\n    <div id=\"email-template-edit-modal\" cla" +
"ss=\"modal modal-medium-wide hide fade\">\r\n        <div class=\"modal-header\">\r\n   " +
"         <a href=\"#\" class=\"close\" data-bind=\"click: raiseClose\">×</a>\r\n        " +
"    <h3>");


            
            #line 10 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
           Write(Resources.EditTemplate);

            
            #line default
            #line hidden
WriteLiteral(@"</h3>
        </div>
        <div id=""email-template-edit-forms-container"" class=""modal-body modal-body-scrollable"">
            <div data-bind=""error: GeneralErrors""></div>
            <form id=""rename-email-template-form"">
                <fieldset>
                    <div class=""clearfix"">
                        ");


            
            #line 17 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                   Write(Html.LabelFor(model => model.Name, Resources.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input input-small-margin\">\r\n               " +
"             ");


            
            #line 19 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                       Write(Html.TextBoxFor(model => model.Name, new { @data_val = "true", @data_val_required = "'Name' should not be empty.", @data_val_length = "'Name' must be a string with a maximum length of 64.", @data_val_length_max = "64", @data_bind = "value: Name" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <button type=\"submit\" class=\"btn btn-primary\" data-" +
"bind=\"click: saveName\">");


            
            #line 20 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                                                                                                 Write(Resources.Rename);

            
            #line default
            #line hidden
WriteLiteral(@"</button>
                            <div data-valmsg-for=""Name"" data-valmsg-replace=""true"" data-bind=""error: NameErrors""></div>
                        </div>
                    </div>
                </fieldset>
            </form>
            <form id=""update-from-address-email-template-form"">
                <fieldset>
                    <div class=""clearfix"">
                        ");


            
            #line 29 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                   Write(Html.LabelFor(model => model.From, Resources.From));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input input-small-margin\">\r\n               " +
"             ");


            
            #line 31 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                       Write(Html.TextBoxFor(model => model.From, new { @data_val = "true", @data_val_required = "'From' should not be empty.", @data_val_email = "'From' is not a valid email address.", @data_val_length = "'From' must be a string with a maximum length of 128.", @data_val_length_max = "128", @data_bind = "value: From" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <button type=\"submit\" class=\"btn btn-primary\" data-" +
"bind=\"click: saveFromAddress\">");


            
            #line 32 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                                                                                                        Write(Resources.Rename);

            
            #line default
            #line hidden
WriteLiteral(@"</button>
                            <div data-valmsg-for=""From"" data-valmsg-replace=""true"" data-bind=""error: FromErrors""></div>
                        </div>
                    </div>
                </fieldset>
            </form>
            <form id=""update-email-content-email-template-form"">
                <fieldset>
                    <div class=""clearfix"">
                        ");


            
            #line 41 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                   Write(Html.LabelFor(model => model.Subject, Resources.Subject));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input input-small-margin\">\r\n               " +
"             ");


            
            #line 43 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                       Write(Html.TextBoxFor(model => model.Subject, new { @data_val = "true", @data_val_required = "'Subject' should not be empty.", @data_val_length = "'Subject' must be a string with a maximum length of 255.", @data_val_length_max = "255", @data_bind = "value: Subject" }));

            
            #line default
            #line hidden
WriteLiteral(@"
                            <div data-valmsg-for=""Subject"" data-valmsg-replace=""true"" data-bind=""error: SubjectErrors""></div>
                        </div>
                    </div>
                    <div class=""clearfix"">
                        ");


            
            #line 48 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                   Write(Html.LabelFor(model => model.Body, Resources.Body));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input input-small-margin\">\r\n               " +
"             ");


            
            #line 50 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                       Write(Html.TextAreaFor(model => model.Body, new { @data_val = "true", @data_val_required = "'Body' should not be empty.", @data_bind = "value: Body" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div data-valmsg-for=\"Body\" data-valmsg-replace=\"tr" +
"ue\" data-bind=\"error: BodyErrors\"></div>\r\n                        </div>\r\n      " +
"              </div>\r\n                    <div class=\"clearfix\">\r\n              " +
"          ");


            
            #line 55 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                   Write(Html.LabelFor(model => model.IsHtml, Resources.Html));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input input-small-margin\">\r\n               " +
"             ");


            
            #line 57 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                       Write(Html.CheckBoxFor(model => model.IsHtml, new { @data_bind = "value: IsHtml" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div data-valmsg-for=\"IsHtml\" data-valmsg-replace=\"" +
"true\" data-bind=\"error: IsHtmlErrors\"></div>\r\n                        </div>\r\n  " +
"                  </div>\r\n                    <div class=\"clearfix\">\r\n          " +
"              ");


            
            #line 62 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                   Write(Html.LabelFor(model => model.Encoding, Resources.Encoding));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input input-small-margin\">\r\n               " +
"             ");


            
            #line 64 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                       Write(Html.EnumDropDownListFor(model => model.Encoding));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <button type=\"submit\" class=\"btn btn-primary\" data-" +
"bind=\"click: saveTemplateContent\">");


            
            #line 65 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                                                                                                            Write(Resources.Update);

            
            #line default
            #line hidden
WriteLiteral(@"</button>
                            <div data-valmsg-for=""Encoding"" data-valmsg-replace=""true"" data-bind=""error: EncodingErrors""></div>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class=""modal-footer"">
            <button type=""submit"" class=""btn btn-info"" data-bind=""click: raiseDetails"">Details</button>&nbsp;
            <button type=""submit"" class=""btn btn-danger"" data-bind=""click: raiseDelete"">");


            
            #line 74 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                                                                                   Write(Resources.Delete);

            
            #line default
            #line hidden
WriteLiteral("</button>&nbsp;\r\n            <button type=\"submit\" class=\"btn btn-danger\" data-bi" +
"nd=\"click: raiseClose\">");


            
            #line 75 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
                                                                                  Write(Resources.Cancel);

            
            #line default
            #line hidden
WriteLiteral("</button>&nbsp;\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");


            
            #line 80 "..\..\Views\EmailTemplateManagement\Edit.cshtml"
   
  using (Html.BeginScriptContext())
  {
    Html.AddScriptBlock(@"
        var email_template_edit = {};

        (function (index) {

            email_template_edit = index;

            var val = ko.setupValidation([], []);
            val.createErrorCollections({Name: 0, From: 0, Subject: 0, Body: 0, IsHtml: 0, Encoding: 0, General: 0}, index, 'email-template-edit-forms-container');

            index.Id = ko.observable();
            index.Name = ko.observable();
            index.ApplicationName = ko.observable();
            index.From = ko.observable();
            index.Subject = ko.observable();
            index.Body = ko.observable();
            index.IsHtml = ko.observable();
            index.Encoding = ko.observable();

            index.saveName = function (form) {
                if(!jQuery('#rename-email-template-form').valid())
                    return;

                jQuery.post('" + @Url.Action("Rename", "Template") + @"', {
                    'id': index.Id(),
                    'name': index.Name()
                }, function (dataReturned) {
                    if (dataReturned.IsValid) {
                        jQuery(document).trigger('emailTemplateUpdated', [dataReturned.Id]);
                    }
                    else {
                        val.rebindValidations({Name: 0, From: 0, Subject: 0, Body: 0, IsHtml: 0, Encoding: 0, General: 0}, index, dataReturned.Errors);
                    }
                });
            };

            index.saveFromAddress = function (form) {
                if(!jQuery('#update-from-address-email-template-form').valid())
                    return;

                jQuery.post('" + @Url.Action("RenameFromAddress", "Template") + @"', {
                    'id': index.Id(),
                    'from': index.From()
                }, function (dataReturned) {
                    if (dataReturned.IsValid) {
                        jQuery(document).trigger('emailTemplateUpdated', [dataReturned.Id]);
                    }
                    else {
                        val.rebindValidations({Name: 0, From: 0, Subject: 0, Body: 0, IsHtml: 0, Encoding: 0, General: 0}, index, dataReturned.Errors);
                    }
                });
            };

            index.saveTemplateContent = function (form) {
                if(!jQuery('#update-email-content-email-template-form').valid())
                    return;

                jQuery.post('" + @Url.Action("Update", "Template") + @"', {
                    'id': index.Id(),
                    'subject': index.Subject(),
                    'body': index.Body(),
                    'isHtml': index.IsHtml(),
                    'encoding': 'ASCII'
                }, function (dataReturned) {
                    if (dataReturned.IsValid) {
                        jQuery(document).trigger('emailTemplateUpdated', [dataReturned.Id]);
                    }
                    else {
                        val.rebindValidations({Name: 0, From: 0, Subject: 0, Body: 0, IsHtml: 0, Encoding: 0, General: 0}, index, dataReturned.Errors);
                    }
                });
            };

            index.raiseDetails = function () {
                index.editModal.modal('hide');
                jQuery(document).trigger('emailTemplateDetails', [index]);
            };

            index.raiseDelete = function () {
                index.editModal.modal('hide');
                jQuery(document).trigger('emailTemplateDelete', [index.Id()]);
            };

            index.raiseClose = function () {
                index.editModal.modal('hide');
            };

            jQuery(document).bind('emailTemplateEdit', function (event, id) {

                jQuery.getJSON('" + @Url.Action("Get", "TemplateManagement") + @"', { id: id }, function (data) {

                    index.Id(data.Id);
                    index.Name(data.Name);
                    index.ApplicationName(data.ApplicationName);
                    index.From(data.From);
                    index.Subject(data.Subject);
                    index.Body(data.Body);
                    index.IsHtml(data.IsHtml);
                    index.Encoding(data.Encoding);

                    index.editModal.modal('show');
                });
            });

            jQuery(function () {
                ko.applyBindings(index, jQuery('#edit-template-container')[0]);
                index.editModal = jQuery('#email-template-edit-modal').modal({ backdrop: true, closeOnEscape: true, modal: true, show: false });
            });
        } (email_template_edit));");
  }

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
