ALTER TABLE [dbo].[EmailDispatchViewEmailMessage]
    ADD CONSTRAINT [PK_EmailDispatchViewEmailMessage] PRIMARY KEY CLUSTERED ([EmailMessageId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

