ALTER TABLE [dbo].[EmailTemplateWidgetTemplate]
    ADD CONSTRAINT [PK_EmailTemplateWidgetTemplate] PRIMARY KEY CLUSTERED ([TemplateId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

