#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.Email.Dashboard.DispatchMonthly.Frontend.Views.DispatchMonthly
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    
    #line 1 "..\..\Views\DispatchMonthly\MonthlyStatistic.cshtml"
    using ThreeBytes.Email.Dashboard.DispatchMonthly.Frontend.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DispatchMonthly/MonthlyStatistic.cshtml")]
    public class MonthlyStatistic : System.Web.Mvc.WebViewPage<DispatchStatisticViewModel>
    {
        public MonthlyStatistic()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n<div id=\"monthly-email-dispatch-statistic-container\" class=\"stat\">\r\n    <h4>Dis" +
"patched Emails This Month</h4>\r\n    <span class=\"value\">");


            
            #line 6 "..\..\Views\DispatchMonthly\MonthlyStatistic.cshtml"
                   Write(Model.CurrentStatistic);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
