#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.Email.About.Frontend.Views.About.Mobile
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/About/Mobile/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<div id=""about"" data-role=""page"">
 
  <div data-role=""header"">
    <h1>About</h1>
  </div>
 
  <div data-role=""content""> 
    <p>About ThreeBytes Email.</p>
    <a href=""/"" rel=""external"" data-role=""button"" data-theme=""a"" data-icon=""arrow-l"">Back</a>
  </div>
 
  <div data-role=""footer"">
    <h4>Designed and built by <a href=""http://www.threebytes.co.uk"" target=""_blank"">Three Bytes</a>.</h4>
  </div>

</div>");


        }
    }
}
#pragma warning restore 1591
