#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.ProjectHollywood.News.List.Frontend.Views.NewsList.Mobile
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Script.Serialization;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    using ThreeBytes.Core.Security.Concrete;
    using ThreeBytes.ProjectHollywood.News.List.Frontend.Models;
    using ThreeBytes.ProjectHollywood.News.List.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/NewsList/Mobile/List.cshtml")]
    public class List : System.Web.Mvc.WebViewPage<PagedNewsListNewsArticleViewModel>
    {
        public List()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div id=\"latest-news-articles-container\">\r\n    <div data-bind=\"latestItems: lat" +
"estViewModel\"></div>\r\n</div>\r\n<div id=\"paged-news-articles-container\">\r\n    <div" +
" data-bind=\"pagedList: pagedViewModel, pagedListTemplate: \'paged-news-articles-t" +
"able-tmpl\'\"></div>\r\n</div>\r\n\r\n<script type=\"text/x-jquery-tmpl\" id=\"paged-news-a" +
"rticles-table-tmpl\">\r\n    <div class=\"content-primary\">\t\t\t\t\t\r\n        <div id=\"p" +
"aged-news-articles-container\">\r\n            <ul data-role=\"listview\" data-inset=" +
"\"true\" class=\"ui-listview ui-listview-inset ui-corner-all ui-shadow\">\r\n\t\t\t    <l" +
"i data-bind=\"visible: items().length > 0, foreach: items\" data-corners=\"false\" d" +
"ata-shadow=\"false\" data-iconshadow=\"true\" data-wrapperels=\"div\" data-icon=\"arrow" +
"-r\" data-iconpos=\"right\" data-theme=\"c\" class=\"ui-btn ui-btn-icon-right ui-li-ha" +
"s-arrow ui-li ui-corner-top ui-btn-up-c\">\r\n                    <div class=\"ui-bt" +
"n-inner ui-li ui-corner-top\">\r\n                        <div class=\"ui-btn-text\">" +
"\r\n                            <a href=\"#\" data-bind=\"click: function(event) { $p" +
"arent.additionalFunctions.raiseDetails($data); }\" class=\"ui-link-inherit\">\r\n    " +
"                            <p class=\"ui-li-aside ui-li-desc\">Created: <span dat" +
"a-bind=\"fadeInText: CreationDateTime\"></span></p>\r\n\t\t\t\t                <h3 data-" +
"bind=\"fadeInText: Title\" class=\"ui-li-heading\"></h3>\r\n\t\t\t\t                <p cla" +
"ss=\"ui-li-desc\"><strong>Created By: <span data-bind=\"fadeInText: CreatedBy\"></sp" +
"an></strong></p>\r\n\t\t\t\t                <p class=\"ui-li-desc\" data-bind=\"fadeInTex" +
"t: Content\"></p>\r\n\t\t\t\t            </a>\r\n                        </div>\r\n        " +
"                <span class=\"ui-icon ui-icon-arrow-r ui-icon-shadow\">&nbsp;</spa" +
"n>\r\n                    </div>\r\n                </li>\r\n\t\t    </ul>\r\n        </di" +
"v>\r\n    </div>\r\n</script>\r\n\r\n");


            
            #line 32 "..\..\Views\NewsList\Mobile\List.cshtml"
   
    using (Html.BeginScriptContext())
    {
        Html.AddScriptBlock(@"
        var news_articles_latest_list  = {};
    
        (function (index) {

            var itemMapping = {
			    'CreationDateTime': ko.utils.getTimeAgoFromJson(),
                'LastModifiedDateTime': ko.utils.getDateFromJson('dd/MMM HH:mm')
		    };

            var itemViewModel = function(data) {
			    ko.mapping.fromJS(data, itemMapping, this);
		    };

            var mapping = {	
			    'Items': {
				    create: function(options) {
					    return new itemViewModel(options.data);
				    }
			    }
		    };
        
            news_articles_latest_list = index = ko.mapping.fromJS(" + @Html.Raw(new JavaScriptSerializer().Serialize(Model.MostRecentResult)) + @", mapping);

            index.latestViewModel = new ko.latestItems.viewModel({
                controller: 'News/List',
                action: 'GetNewerThan',
                data: index,
                singular: '" + @Resources.NewsArticle + @"',
                plural: '" + @Resources.NewsArticles + @"',
                loadPageCallback: function(data) {
                    ko.mapping.fromJS(data, index);
                },
                divIdentifier: 'latest-news-articles-container',
                pagingComponentIdentifier: 'paged-news-articles',
                columns: [
                    { headerText: 'Created By', rowText: 'CreatedBy' },
                    { headerText: 'Created On', rowText: 'CreationDateTime' },
                    { headerText: 'Title', rowText: 'Title' }
                ]
            });

            jQuery(function() {
                ko.applyBindings(index, jQuery('#latest-news-articles-container')[0]);
            });
        
        } (news_articles_latest_list));
    
        var news_articles_list  = {};

        (function (index) {

            var itemMapping = {
			    'CreationDateTime': ko.utils.getTimeAgoFromJson(),
                'LastModifiedDateTime': ko.utils.getDateFromJson('dd/MMM HH:mm')
		    };

            var itemViewModel = function(data) {
			    ko.mapping.fromJS(data, itemMapping, this);
		    };

            var mapping = {	
			    'Items': {
				    create: function(options) {
					    return new itemViewModel(options.data);
				    }
			    }
		    };
        
            news_articles_list = index = ko.mapping.fromJS(" + @Html.Raw(new JavaScriptSerializer().Serialize(Model.PagedResult)) + @", mapping);

            index.HighlightEdits = ko.observable(false);

            index.pagedViewModel = new ko.pagedList.viewModel({
                controller: 'News',
                action: 'GetPage',
                data: index,
                singular: '" + @Resources.NewsArticle + @"',
                plural: '" + @Resources.NewsArticles + @"',
                pagingComponentIdentifier: 'paged-news-articles',
                loadPageCallback: function(data) {
                    ko.mapping.fromJS(data, index);
                },
                columns: [
                    { headerText: 'Created By', rowText: 'CreatedBy' },
                    { headerText: 'Created On', rowText: 'CreationDateTime' },
                    { headerText: 'Title', rowText: 'Title' },
                    { headerText: 'Content', rowText: 'Content' }
                ],
                additionalFunctions: {
                    raiseEdit: function (obj) {
                        jQuery(document).trigger('newsArticleEdit', [obj.Id()]);
                    },
                    raiseDetails: function (obj) {
                        jQuery(document).trigger('newsArticleDetails', [obj]);
                    },
                    raiseDelete: function (obj) {
                        jQuery(document).trigger('newsArticleDelete', [obj.Id()]);
                    }
                },
                updateEvent: null,
                deleteEvent: null
            });

            var hub = jQuery.connection.newsListHub;

            hub.handleRenamedNewsArticleTitleEventMessage = function(id, newTitle) {
                var update = ko.utils.arrayFirst(index.Items(), function(item) {
                    return item.Id() == id;
                });

                if (update == null)
                    return;

                if (update.Title() == newTitle)
                    return;
                
                ko.bindingHandlers.fadeInText.highlight = true;
                update.Title(newTitle);
                ko.bindingHandlers.fadeInText.highlight = false;
            };

            hub.handleUpdatedNewsArticleContentEventMessage = function(id, newContent) {
                var update = ko.utils.arrayFirst(index.Items(), function(item) {
                    return item.Id() == id;
                });

                if (update == null)
                    return;

                if (update.Content() == newContent)
                    return;

                ko.bindingHandlers.fadeInText.highlight = true;
                update.Content(newContent);
                ko.bindingHandlers.fadeInText.highlight = false;
            };

            hub.handleDeletedNewsArticleEventMessage = function(id) {
                var toDelete = ko.utils.arrayFirst(index.Items(), function(item) {
                    return item.Id() == id;
                });

                if (toDelete == null)
                    return;

                index.Items.remove(toDelete);
                index.TotalItemCount((index.TotalItemCount() - 1))
            };

            jQuery(function() {
                ko.applyBindings(index, jQuery('#paged-news-articles-container')[0]);
            });

        } (news_articles_list));");
    }


            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
