#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.User.Role.View.FrontEnd.Views.RoleView
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    using ThreeBytes.User.Role.View.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/RoleView/Details.cshtml")]
    public class Details : System.Web.Mvc.WebViewPage<ThreeBytes.User.Role.View.Entities.RoleViewRole>
    {
        public Details()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\RoleView\Details.cshtml"
  
    ViewBag.Title = Resources.BrowserTitleDetails;


            
            #line default
            #line hidden
WriteLiteral(@"
<div id=""user-role-details-container"">
    <div id=""user-role-details-modal"" class=""modal modal-medium-wide hide fade"">
        <div class=""modal-header"">
            <a href=""#"" class=""close"" data-bind=""click: raiseClose"">×</a>
            <h3>
                <span data-bind=""text:Name""></span> ");


            
            #line 11 "..\..\Views\RoleView\Details.cshtml"
                                               Write(Resources.Details);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </h3>\r\n        </div>\r\n        <div class=\"modal-body modal-body-sc" +
"rollable\">\r\n            <div class=\"row\">\r\n                <div class=\"span12 co" +
"lumns\">\r\n                    <div class=\"display-label\">");


            
            #line 17 "..\..\Views\RoleView\Details.cshtml"
                                          Write(Resources.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div class=\"display-field\"><span data-bind=\"text:Name" +
"\"></span></div>\r\n\r\n                    <div class=\"display-label\">");


            
            #line 20 "..\..\Views\RoleView\Details.cshtml"
                                          Write(Resources.ApplicationName);

            
            #line default
            #line hidden
WriteLiteral(@"</div>
                    <div class=""display-field""><span data-bind=""text:ApplicationName""></span></div>
                </div>
            </div>
            <div id=""user-role-history-container"" class=""row"" data-bind=""visible: History().length > 0"">
                <div class=""span9 columns"">
                    <h2>");


            
            #line 26 "..\..\Views\RoleView\Details.cshtml"
                   Write(Resources.History);

            
            #line default
            #line hidden
WriteLiteral(@"</h2>
                    <table class=""table table-striped table-bordered table-condensed scrollable"">
                        <thead>
                            <tr>
                                <th>Date Time</th>
                                <th>");


            
            #line 31 "..\..\Views\RoleView\Details.cshtml"
                               Write(Resources.Name);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th>");


            
            #line 32 "..\..\Views\RoleView\Details.cshtml"
                               Write(Resources.Operation);

            
            #line default
            #line hidden
WriteLiteral(@"</th>
                            </tr>
                        </thead>
                        <tbody id=""user-role-tbody"" data-bind=""foreach: History"">
                            <tr>        
                                <td data-bind=""text: GetDate(LastModifiedDateTime)""></td>
                                <td data-bind=""text: Name""></td>
                                <td data-bind=""text: Operation""></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class=""modal-footer"">
            <button class=""btn btn-primary"" data-bind=""click: raiseEdit"">");


            
            #line 47 "..\..\Views\RoleView\Details.cshtml"
                                                                    Write(Resources.Edit);

            
            #line default
            #line hidden
WriteLiteral("</button>.\r\n            <button class=\"btn btn-danger\" data-bind=\"click: raiseClo" +
"se\">Close</button>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");


            
            #line 53 "..\..\Views\RoleView\Details.cshtml"
   
  using (Html.BeginScriptContext())
  {
    Html.AddScriptBlock(@"
        var user_role_details = {};

        (function (index) {

            user_role_details = index;

            index.Id = ko.observable();
            index.ItemId = ko.observable();
            index.Name = ko.observable();
            index.ApplicationName = ko.observable();
            index.History = ko.observableArray();

            index.raiseClose = function () {
                index.detailModal.modal('hide');
            };

            index.raiseEdit = function (obj) {
                index.detailModal.modal('hide');
                jQuery(document).trigger('userRoleEdit', index.ItemId());
            };

            jQuery(document).bind('userRoleDetails', function (event, role) {

                jQuery.getJSON('" + @Url.Action("GetDetails", "Roles") + @"', { id: role.Id() }, function (data) {

                    index.Id(data.Id);
                    index.ItemId(data.ItemId);
                    index.Name(data.Name);
                    index.ApplicationName(data.ApplicationName);
                    index.History(data.History);

                    index.detailModal.modal('show');
                });
            });

            jQuery(function () {
                ko.applyBindings(index, jQuery('#user-role-details-container')[0]);
                index.detailModal = jQuery('#user-role-details-modal').modal({ backdrop: true, closeOnEscape: true, modal: true, show: false });
            });
        } (user_role_details));");
  }

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
