#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.ProjectHollywood.About.Frontend.Views.About.Mobile
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/About/Mobile/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {

DefineSection("Header", () => {

WriteLiteral("\r\n    <h1>About Us</h1>\r\n");


});

WriteLiteral("\r\n\r\n<div id=\"about-content\">\r\n    <div class=\"row\">\r\n        <div class=\"span12\">" +
"\r\n            <ul data-role=\"listview\" data-inset=\"true\" class=\"ui-listview ui-l" +
"istview-inset ui-corner-all ui-shadow\">\r\n\t\t\t    <li data-corners=\"false\" data-sh" +
"adow=\"false\" data-iconshadow=\"true\" data-wrapperels=\"div\" data-icon=\"arrow-r\" da" +
"ta-iconpos=\"right\" data-theme=\"c\" class=\"ui-btn ui-btn-icon-right ui-li-has-arro" +
"w ui-li ui-corner-top ui-btn-up-c\">\r\n                    <div class=\"ui-li ui-co" +
"rner-top\">\r\n                        <div class=\"ui-btn-text\">\r\n                 " +
"            <p class=\"ui-li-desc\">\r\n                                FELIX DE WOL" +
"FE, one of the longest established independent entertainment and literary agenci" +
"es in the United Kingdom. \r\n                                Over the past sixty " +
"plus years, the agency has, and continues to look after some of the country’s mo" +
"st talented performers, writers and directors, whose works encompass a wide spec" +
"trum of the arts.\r\n                            </p>\r\n                           " +
" <p class=\"ui-li-desc\">\r\n                                The agency prides itsel" +
"f on the quality of its client base and continues to be one of the frontrunners " +
"in the entertainment business today.\r\n                            </p>\r\n        " +
"                    <p class=\"ui-li-desc\">\r\n                                Our " +
"exclusive client base includes actors, actresses, presenters, directors and comp" +
"osers, as well as authors and writers for film, television, stage and radio.\r\n  " +
"                          </p>\r\n                            <p class=\"ui-li-desc" +
"\">\r\n                                Felix de Wolfe is a member of the PMA (Perso" +
"nal Managers Association); the late Felix de Wolfe himself was the Chair of the " +
"organisation for many years.\r\n                            </p>\r\n                " +
"        </div>\r\n                    </div>\r\n                </li>\r\n\t\t    </ul>\r\n" +
"            <p>\r\n                <a href=\"#american-contacts-page\" data-role=\"bu" +
"tton\" data-theme=\"b\" data-rel=\"dialog\" data-transition=\"flow\">American Contacts<" +
"/a>\r\n            </p>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");


DefineSection("OtherPages", () => {

WriteLiteral(@"
    <div data-role=""page"" id=""american-contacts-page"">
        <div data-role=""header"">
            <h1>American Contacts</h1>
        </div>
        <div data-role=""content"">
            <p>
                We enjoy non-exclusive affiliations with both East and West Coast agents and managers including:

                <ul>
                    <li>Abrams Artists</li>
                    <li>Alan Siegel Entertainment</li>
                    <li>Andy Howard</li>
                    <li>APA</li>
                    <li>Don Buchwald & Associates</li>
                    <li>Gage Group</li>
                    <li>Gersh Agency</li>
                    <li>Hartig Hilepo</li>
                    <li>Innovative Artists</li>
                    <li>Louisa Spring</li>
                    <li>Paradigm</li>
                    <li>Rough Diamond</li>
                    <li>Vincent Cirrincione Associates</li>
                </ul>
            </p>
        </div>
        <div data-role=""footer""></div>
    </div>
");


});


        }
    }
}
#pragma warning restore 1591
