#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.ProjectHollywood.Contact.Frontend.Views.Contact.Mobile
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Contact/Mobile/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {

DefineSection("Header", () => {

WriteLiteral("\r\n    <h1>Contact Us</h1>\r\n");


});

WriteLiteral("\r\n\r\n<div id=\"contact-us-content\">\r\n    <div class=\"row\">\r\n        <div class=\"spa" +
"n12\">\r\n            <div id=\"contact-us-address-container\">\r\n                <ul " +
"data-role=\"listview\" data-inset=\"true\" class=\"ui-listview ui-listview-inset ui-c" +
"orner-all ui-shadow\">\r\n\t\t\t        <li data-corners=\"false\" data-shadow=\"false\" d" +
"ata-iconshadow=\"true\" data-wrapperels=\"div\" data-icon=\"arrow-r\" data-iconpos=\"ri" +
"ght\" data-theme=\"c\" class=\"ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-cor" +
"ner-top ui-btn-up-c\">\r\n                        <div class=\"ui-li ui-corner-top\">" +
"\r\n                            <div class=\"ui-btn-text\">\r\n\t\t\t\t                <h3" +
" class=\"ui-li-heading\">Address</h3>\r\n                                <p class=\"u" +
"i-li-desc\">Kingsway House</p>\r\n                                <p class=\"ui-li-d" +
"esc\">103 Kingsway</p>\r\n                                <p class=\"ui-li-desc\">Lon" +
"don</p>\r\n                                <p class=\"ui-li-desc\">WC2B 6QX</p>\r\n   " +
"                         </div>\r\n                        </div>\r\n               " +
"     </li>\r\n\t\t        </ul>\r\n            </div>\r\n            <div id=\"contact-us" +
"-phone-container\">\r\n                <ul data-role=\"listview\" data-inset=\"true\" c" +
"lass=\"ui-listview ui-listview-inset ui-corner-all ui-shadow\">\r\n\t\t\t        <li da" +
"ta-corners=\"false\" data-shadow=\"false\" data-iconshadow=\"true\" data-wrapperels=\"d" +
"iv\" data-icon=\"arrow-r\" data-iconpos=\"right\" data-theme=\"c\" class=\"ui-btn ui-btn" +
"-icon-right ui-li-has-arrow ui-li ui-corner-top ui-btn-up-c\">\r\n                 " +
"       <div class=\"ui-li ui-corner-top\">\r\n                            <div class" +
"=\"ui-btn-text\">\r\n\t\t\t\t                <h3 class=\"ui-li-heading\">Phone Numbers</h3" +
">\r\n                                <p class=\"ui-li-desc\">Tel: 020 7242 5066</p>\r" +
"\n                                <p class=\"ui-li-desc\">Fax: 020 7242 8119</p>\r\n " +
"                           </div>\r\n                        </div>\r\n             " +
"       </li>\r\n\t\t        </ul>\r\n            </div>\r\n            <div id=\"contact-" +
"us-email-container\">\r\n                <ul data-role=\"listview\" data-inset=\"true\"" +
" class=\"ui-listview ui-listview-inset ui-corner-all ui-shadow\">\r\n\t\t\t        <li " +
"data-corners=\"false\" data-shadow=\"false\" data-iconshadow=\"true\" data-wrapperels=" +
"\"div\" data-icon=\"arrow-r\" data-iconpos=\"right\" data-theme=\"c\" class=\"ui-btn ui-b" +
"tn-icon-right ui-li-has-arrow ui-li ui-corner-top ui-btn-up-c\">\r\n               " +
"         <div class=\"ui-li ui-corner-top\">\r\n                            <div cla" +
"ss=\"ui-btn-text\">\r\n\t\t\t\t                <h3 class=\"ui-li-heading\">Email</h3>\r\n   " +
"                             <p class=\"ui-li-desc\"><a href=\"mailto:email@felixde" +
"wolfe.com\">email@felixdewolfe.com</a></p>\r\n                            </div>\r\n " +
"                       </div>\r\n                    </li>\r\n\t\t        </ul>\r\n     " +
"       </div>\r\n            <div id=\"contact-us-address-container\">\r\n            " +
"    <ul data-role=\"listview\" data-inset=\"true\" class=\"ui-listview ui-listview-in" +
"set ui-corner-all ui-shadow\">\r\n\t\t\t        <li data-corners=\"false\" data-shadow=\"" +
"false\" data-iconshadow=\"true\" data-wrapperels=\"div\" data-icon=\"arrow-r\" data-ico" +
"npos=\"right\" data-theme=\"c\" class=\"ui-btn ui-btn-icon-right ui-li-has-arrow ui-l" +
"i ui-corner-top ui-btn-up-c\">\r\n                        <div class=\"ui-li ui-corn" +
"er-top\">\r\n                            <div class=\"ui-btn-text\">\r\n\t\t\t\t           " +
"     <h3 class=\"ui-li-heading\">Company Details</h3>\r\n\t\t\t\t                <p clas" +
"s=\"ui-li-desc\">Felix de Wolfe Limited</p>\r\n                                <p cl" +
"ass=\"ui-li-desc\">Registered in England: 32295323</p>\r\n                          " +
"      <p class=\"ui-li-desc\">Acorn Business Centre</p>\r\n                         " +
"       <p class=\"ui-li-desc\">Northarbour Road</p>\r\n                             " +
"   <p class=\"ui-li-desc\">Cosham</p>\r\n                                <p class=\"u" +
"i-li-desc\">Portsmouth</p>\r\n                                <p class=\"ui-li-desc\"" +
">P06 3TH</p>\r\n                                <p class=\"ui-li-desc\">VAT Registra" +
"tion No. GB 238 718 830</p>\r\n                            </div>\r\n               " +
"         </div>\r\n                    </li>\r\n\t\t        </ul>\r\n            </div>\r" +
"\n\r\n            <div data-role=\"collapsible\" data-theme=\"a\" data-content-theme=\"a" +
"\">\r\n               <h3>Map</h3>\r\n               <iframe width=\"100%\" height=\"300" +
"\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\" src=\"http://ma" +
"ps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=felix+de+wo" +
"lfe+London&amp;aq=&amp;sll=51.559871,-0.112181&amp;sspn=0.011939,0.033023&amp;vp" +
"src=0&amp;ie=UTF8&amp;hq=felix+de+wolfe&amp;hnear=London,+United+Kingdom&amp;t=m" +
"&amp;z=14&amp;iwloc=A&amp;cid=17154246103610845139&amp;ll=51.516386,-0.12012&amp" +
";output=embed\"></iframe>\r\n                <br />\r\n                <small>\r\n     " +
"               <a href=\"http://maps.google.co.uk/maps?f=q&amp;source=embed&amp;h" +
"l=en&amp;geocode=&amp;q=felix+de+wolfe+London&amp;aq=&amp;sll=51.559871,-0.11218" +
"1&amp;sspn=0.011939,0.033023&amp;vpsrc=0&amp;ie=UTF8&amp;hq=felix+de+wolfe&amp;h" +
"near=London,+United+Kingdom&amp;t=m&amp;z=14&amp;iwloc=A&amp;cid=171542461036108" +
"45139&amp;ll=51.516386,-0.12012\" style=\"color:#0000FF;text-align:right\" class=\"p" +
"ull-right\">View Larger Map</a>\r\n                </small>\r\n            </div>\r\n  " +
"      </div>      \r\n    </div>\r\n</div>\r\n\r\n");


            
            #line 81 "..\..\Views\Contact\Mobile\Index.cshtml"
  
  using (var context = Html.BeginScriptContext())
  {
      context.ScriptFiles.Add("http://maps.google.com/maps/api/js?sensor=false");
  }   

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
