#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.ProjectHollywood.News.Management.Frontend.Views.NewsManagement
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    using ThreeBytes.Core.Security.Concrete;
    using ThreeBytes.ProjectHollywood.News.Management.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/NewsManagement/Create.cshtml")]
    public class Create : System.Web.Mvc.WebViewPage<ThreeBytes.ProjectHollywood.News.Management.Entities.NewsManagementNewsArticle>
    {
        public Create()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Views\NewsManagement\Create.cshtml"
 if (Context.User.Identity.IsAuthenticated && ((ThreeBytesPrincipal)Context.User).IsInAnyRoles(new[] { "Creator", "Admin", "NewsManager" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <div id=\"create-news-article-container\">\r\n        <p>\r\n            <button cl" +
"ass=\"btn btn-primary\" data-bind=\"click: raiseCreate\" rel = \"popover\" data_conten" +
"t =\"");


            
            #line 7 "..\..\Views\NewsManagement\Create.cshtml"
                                                                                                     Write(Resources.CreatePopoverContent);

            
            #line default
            #line hidden
WriteLiteral("\" data_original_title =\"");


            
            #line 7 "..\..\Views\NewsManagement\Create.cshtml"
                                                                                                                                                            Write(Resources.CreatePopoverTitle);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 7 "..\..\Views\NewsManagement\Create.cshtml"
                                                                                                                                                                                           Write(Resources.Create);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n        </p>\r\n        <div id=\"create-news-article-modal\" class=\"modal" +
" modal-medium-wide hide fade\">\r\n            <div class=\"modal-header\">\r\n        " +
"        <a href=\"#\" class=\"close\" data-bind=\"click: raiseClose\">×</a>\r\n         " +
"       <h3>");


            
            #line 12 "..\..\Views\NewsManagement\Create.cshtml"
               Write(Resources.CreateNewsArticle);

            
            #line default
            #line hidden
WriteLiteral(@"</h3>
            </div>
            <div class=""modal-body modal-body-scrollable"">
                <div data-bind=""error: GeneralErrors""></div>
                <form id=""create-news-article-form"">
                    <fieldset>
                        <div class=""clearfix"">
                            ");


            
            #line 19 "..\..\Views\NewsManagement\Create.cshtml"
                       Write(Html.LabelFor(model => model.Title, Resources.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div class=\"input input-small-margin\">\r\n           " +
"                     ");


            
            #line 21 "..\..\Views\NewsManagement\Create.cshtml"
                           Write(Html.TextBoxFor(model => model.Title, new { @data_val = "true", @data_val_required = "'Title' should not be empty.", @data_val_length = "'Title' must be a string with a maximum length of 100.", @data_val_length_max = "100", @data_bind = "value: Title" }));

            
            #line default
            #line hidden
WriteLiteral(@"
                                <div data-valmsg-for=""Title"" data-valmsg-replace=""true"" data-bind=""error: TitleErrors""></div>
                            </div>
                        </div>
                        <div class=""clearfix"">
                            ");


            
            #line 26 "..\..\Views\NewsManagement\Create.cshtml"
                       Write(Html.LabelFor(model => model.Content, Resources.Content));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div class=\"input input-small-margin\">\r\n           " +
"                     ");


            
            #line 28 "..\..\Views\NewsManagement\Create.cshtml"
                           Write(Html.TextAreaFor(model => model.Content, new { @data_val = "true", @data_val_required = "'Content' should not be empty.", @data_bind = "value: Content" }));

            
            #line default
            #line hidden
WriteLiteral(@"
                                <div data-valmsg-for=""Content"" data-valmsg-replace=""true"" data-bind=""error: ContentErrors""></div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class=""modal-footer"">
                <button type=""submit"" class=""btn btn-primary"" data-bind=""click: save"">");


            
            #line 36 "..\..\Views\NewsManagement\Create.cshtml"
                                                                                 Write(Resources.SaveChanges);

            
            #line default
            #line hidden
WriteLiteral("</button>&nbsp;\r\n                <button type=\"submit\" class=\"btn btn-danger\" dat" +
"a-bind=\"click: raiseClose\">");


            
            #line 37 "..\..\Views\NewsManagement\Create.cshtml"
                                                                                      Write(Resources.Cancel);

            
            #line default
            #line hidden
WriteLiteral("</button>&nbsp;\r\n            </div>\r\n        </div>\r\n    </div>\r\n");


            
            #line 41 "..\..\Views\NewsManagement\Create.cshtml"

    using (Html.BeginScriptContext())
    {
        Html.AddScriptBlock(@"

        var news_article_create = {};

        (function (index) {

            news_article_create = index;

            var val = ko.setupValidation([], []);
            val.createErrorCollections({Title: 0, Content: 0, General: 0}, index, 'create-news-article-form');

            index.Title = ko.observable();
            index.Content = ko.observable();

            index.toJS = function() {
                return { Title: index.Title(), Content: index.Content() }
            };

            index.raiseCreate = function () {
                index.clear();
                index.createModal.modal('show');
            };

            index.raiseClose = function () {
                index.createModal.modal('hide');
            };

            index.save = function (form) {
                if(!jQuery('#create-news-article-form').valid())
                    return;

                jQuery.post('" + @Url.Action("Create", "News") + @"', index.toJS(), function (dataReturned) {
                    if (dataReturned.IsValid) {
                        jQuery(document).trigger('newsArticleCreated');
                        jQuery(document).trigger('publishProcessingNotification', ['Processing news article creation.', 'We are currently processing your request to create the news article ' + index.Title() + '.']);
                        index.createModal.modal('hide');
                    }
                    else {
                        val.rebindValidations({Title: 0, Content: 0, General: 0}, index, dataReturned.Errors);
                    }
                });
            };

            index.clear = function() {
                index.Title(null);
                index.Content(null);

                val.clearValidations({Title: 0, Content: 0, General: 0}, index);
            };

            jQuery(function () {
                ko.applyBindings(index, jQuery('#create-news-article-container')[0]);
                index.createModal = jQuery('#create-news-article-modal').modal({ backdrop: true, closeOnEscape: true, modal: true, show: false });
            });

        } (news_article_create));");
    }
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
