#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.ProjectHollywood.About.Frontend.Views.About
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/About/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\About\Index.cshtml"
  
    Page.Title = "About";


            
            #line default
            #line hidden
WriteLiteral("\r\n<section id=\"about\">\r\n    <div id=\"about-container\">\r\n        <div class=\"hero-" +
"unit\"> \r\n            <h1>About Us</h1> \r\n        </div>\r\n        <div class=\"row" +
"\">\r\n            <div class=\"span6\">&nbsp;</div>\r\n            <div class=\"span6\">" +
" \r\n                <p>\r\n                    FELIX DE WOLFE, one of the longest e" +
"stablished independent entertainment and literary agencies in the United Kingdom" +
". \r\n                    Over the past sixty plus years, the agency has, and cont" +
"inues to look after some of the country’s most talented performers, writers and " +
"directors, whose works encompass a wide spectrum of the arts.\r\n                <" +
"/p>\r\n                <p>\r\n                    The agency prides itself on the qu" +
"ality of its client base and continues to be one of the frontrunners in the ente" +
"rtainment business today.\r\n                </p>\r\n                <p>\r\n          " +
"          Our exclusive client base includes actors, actresses, presenters, dire" +
"ctors and composers, as well as authors and writers for film, television, stage " +
"and radio.\r\n                </p>\r\n                <p>\r\n                    Felix" +
" de Wolfe is a member of the PMA (Personal Managers Association); the late Felix" +
" de Wolfe himself was the Chair of the organisation for many years.\r\n           " +
"     </p>\r\n                <p>\r\n                    <button class=\"btn btn-prima" +
"ry pull-right\" data-bind=\"click: raiseAmericanContacts\" rel = \"popover\" data_con" +
"tent =\"Holloway | Broadway\" data_original_title =\"American Contacts\">American Co" +
"ntacts</button>\r\n                </p>\r\n            </div>\r\n        </div>\r\n     " +
"   \r\n        <div id=\"american-contacts-modal\" class=\"modal hide fade\">\r\n       " +
"     <div class=\"modal-header\">\r\n                <a href=\"#\" class=\"close\" data-" +
"bind=\"click: raiseClose\">×</a>\r\n                <h3>American Contacts</h3>\r\n    " +
"        </div>\r\n            <div class=\"modal-body\">\r\n                <p>\r\n     " +
"               We enjoy non-exclusive affiliations with both East and West Coast" +
" agents and managers including:\r\n\r\n                    <ul>\r\n                   " +
"     <li>Abrams Artists</li>\r\n                        <li>Alan Siegel Entertainm" +
"ent</li>\r\n                        <li>Andy Howard</li>\r\n                        " +
"<li>APA</li>\r\n                        <li>Don Buchwald & Associates</li>\r\n      " +
"                  <li>Gage Group</li>\r\n                        <li>Gersh Agency<" +
"/li>\r\n                        <li>Hartig Hilepo</li>\r\n                        <l" +
"i>Innovative Artists</li>\r\n                        <li>Louisa Spring</li>\r\n     " +
"                   <li>Paradigm</li>\r\n                        <li>Rough Diamond<" +
"/li>\r\n                        <li>Vincent Cirrincione Associates</li>\r\n         " +
"           </ul>\r\n                </p>\r\n            </div>\r\n            <div cla" +
"ss=\"modal-footer\">\r\n                <button class=\"btn btn-danger\" data-bind=\"cl" +
"ick: raiseClose\">Close</button>\r\n            </div>\r\n        </div>\r\n    </div>\r" +
"\n</section>\r\n\r\n");


            
            #line 65 "..\..\Views\About\Index.cshtml"
   
  using (Html.BeginScriptContext())
  {
    Html.AddScriptBlock(@"
        var about_host = {};

        (function (index) {

            about_host = index;

            index.raiseAmericanContacts = function () {
                index.americanContactsModal.modal('show');
            };

            index.raiseClose = function () {
                index.americanContactsModal.modal('hide');
            };

            jQuery(function () {
                ko.applyBindings(index, jQuery('#about-container')[0]);
                index.americanContactsModal = jQuery('#american-contacts-modal').modal({ backdrop: true, closeOnEscape: true, modal: true, show: false });
            });

        } (about_host));");
  }

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
