#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.User.Authentication.Login.Frontend.Views.Login
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    using ThreeBytes.User.Authentication.Login.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Login/Login.cshtml")]
    public class Login : System.Web.Mvc.WebViewPage<ThreeBytes.User.Authentication.Login.Frontend.Models.LoginViewModel>
    {
        public Login()
        {
        }
        public override void Execute()
        {
WriteLiteral(" ");


WriteLiteral("           \r\n");


            
            #line 3 "..\..\Views\Login\Login.cshtml"
  
    ViewBag.Title = Resources.BrowserTitle;


            
            #line default
            #line hidden
WriteLiteral("\r\n<section id=\"login\">\r\n    <div id=\"login-container\" class=\"account-container\">\r" +
"\n        <div class=\"content clearfix\">\r\n");


            
            #line 10 "..\..\Views\Login\Login.cshtml"
             using (Html.BeginForm("Login", "Login", FormMethod.Post, new { id = "login-form" }))
            {

            
            #line default
            #line hidden
WriteLiteral("                <h1>Sign in</h1>\r\n");



WriteLiteral(@"                <div class=""login-fields"">
                    <p>Sign in using your registered account:</p>
                    <div class=""field"">
                        <label for=""username"">Username:</label>
                        <input type=""text"" id=""username"" name=""username"" value="""" placeholder=""Username"" class=""login username-field"" />
                    </div>
");


            
            #line 19 "..\..\Views\Login\Login.cshtml"
                     if (!ViewData.ModelState.IsValidField("Username"))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div class=\"alert alert-error\">\r\n                        " +
"    <a class=\"close\" data-dismiss=\"alert\">×</a>\r\n                            ");


            
            #line 23 "..\..\Views\Login\Login.cshtml"
                       Write(Html.ValidationMessageFor(model => model.Username));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n");


            
            #line 25 "..\..\Views\Login\Login.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral(@"
                    <div class=""field"">
                        <label for=""password"">Password:</label>
                        <input type=""password"" id=""password"" name=""password"" value="""" placeholder=""Password"" class=""login password-field""/>
                    </div>
");


            
            #line 31 "..\..\Views\Login\Login.cshtml"
                     if (!ViewData.ModelState.IsValidField("Password"))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div class=\"alert alert-error\">\r\n                        " +
"    <a class=\"close\" data-dismiss=\"alert\">×</a>\r\n                            ");


            
            #line 35 "..\..\Views\Login\Login.cshtml"
                       Write(Html.ValidationMessageFor(model => model.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n");


            
            #line 37 "..\..\Views\Login\Login.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral(@"                            
                    <div class=""login-actions"">		
                        <span class=""login-checkbox"">
                            <input id=""rememberMe"" name=""rememberMe"" type=""checkbox"" class=""field login-checkbox"" tabindex=""4"" />
                            <label class=""choice"" for=""rememberMe"">Keep me signed in</label>
                        </span>
									
                        <button class=""button btn btn-warning btn-large"" data-bind=""click: login"">Sign In</button>			
                    </div>
                            
                    <div class=""login-social"">
                        <p>Sign in using social network:</p>
				
                        <div class=""twitter"">
                            <a href=""");


            
            #line 52 "..\..\Views\Login\Login.cshtml"
                                Write(Url.Action("Login", "Foursquare"));

            
            #line default
            #line hidden
WriteLiteral("\">Login with Foursquare</a>\t\r\n                        </div>\r\n\t\t\t\t\r\n             " +
"           <div class=\"fb\">\r\n                            <a href=\"");


            
            #line 56 "..\..\Views\Login\Login.cshtml"
                                Write(Url.Action("Login", "Facebook"));

            
            #line default
            #line hidden
WriteLiteral("\">Login with Facebook</a>\r\n                        </div>\r\n                    </" +
"div>\r\n                </div>\r\n");


            
            #line 60 "..\..\Views\Login\Login.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n    \r\n    <div class=\"login-extra\">\r\n        Don\'t ha" +
"ve an account? <a href=\"");


            
            #line 65 "..\..\Views\Login\Login.cshtml"
                                   Write(Url.Action("Register", "Registration"));

            
            #line default
            #line hidden
WriteLiteral("\">Sign Up</a><br/>\r\n        Remind <a href=\"#\" data-bind=\"click: raiseForgottenPa" +
"sswordOpen\">Password</a>\r\n    </div>\r\n</section>\r\n\r\n");


            
            #line 70 "..\..\Views\Login\Login.cshtml"
   Html.RenderAction("ResetPassword", "PasswordManagement");

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 72 "..\..\Views\Login\Login.cshtml"
   
    using (Html.BeginScriptContext())
    {
        Html.AddScriptBlock(@"
        var login = {};

        (function (index) {

            login = index;

            index.login = function () {
                jQuery('#login-form').submit();
            };

            index.raiseForgottenPasswordOpen = function() {
                jQuery(document).trigger('resetPassword');
            };

            jQuery(function () {
                ko.applyBindings(index, jQuery('#login')[0]);
            });

        } (login));");
    }

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
