//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.User.Authentication.UserManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreeBytes.User.Authentication.UserManagement.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThreeBytes: User Management.
        /// </summary>
        public static string BrowserTitle {
            get {
                return ResourceManager.GetString("BrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User Roles.
        /// </summary>
        public static string CurrentUserRoles {
            get {
                return ResourceManager.GetString("CurrentUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name .
        /// </summary>
        public static string LengthApplicationNameValidationMessage {
            get {
                return ResourceManager.GetString("LengthApplicationNameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name must be at least {0} characters, but less than {1} characters..
        /// </summary>
        public static string LengthRoleNameValidationMessage {
            get {
                return ResourceManager.GetString("LengthRoleNameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Out.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Status.
        /// </summary>
        public static string LockedStatus {
            get {
                return ResourceManager.GetString("LockedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User.
        /// </summary>
        public static string ManageUser {
            get {
                return ResourceManager.GetString("ManageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not have duplicate roles..
        /// </summary>
        public static string MustNotHaveDuplicateRolesValidationMessage {
            get {
                return ResourceManager.GetString("MustNotHaveDuplicateRolesValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Locked Out.
        /// </summary>
        public static string NotLockedOut {
            get {
                return ResourceManager.GetString("NotLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name must be at least {0} characters, but less than {1} characters..
        /// </summary>
        public static string RequiredApplicationNameValidationMessage {
            get {
                return ResourceManager.GetString("RequiredApplicationNameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string RequiredEmailValidationMessage {
            get {
                return ResourceManager.GetString("RequiredEmailValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name is required..
        /// </summary>
        public static string RequiredRoleNameValidationMessage {
            get {
                return ResourceManager.GetString("RequiredRoleNameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        public static string RequiredUsernameValidationMessage {
            get {
                return ResourceManager.GetString("RequiredUsernameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role already exists..
        /// </summary>
        public static string UniqueRoleValidationMessage {
            get {
                return ResourceManager.GetString("UniqueRoleValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists..
        /// </summary>
        public static string UniqueUsernameValidationMessage {
            get {
                return ResourceManager.GetString("UniqueUsernameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Account.
        /// </summary>
        public static string UnlockAccount {
            get {
                return ResourceManager.GetString("UnlockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists..
        /// </summary>
        public static string UnqiueEmailValidationMessage {
            get {
                return ResourceManager.GetString("UnqiueEmailValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Verified.
        /// </summary>
        public static string UnVerified {
            get {
                return ResourceManager.GetString("UnVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a correct email format..
        /// </summary>
        public static string ValidEmailValidationMessage {
            get {
                return ResourceManager.GetString("ValidEmailValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Status:.
        /// </summary>
        public static string VerifiedStatus {
            get {
                return ResourceManager.GetString("VerifiedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Account.
        /// </summary>
        public static string VerifyAccount {
            get {
                return ResourceManager.GetString("VerifyAccount", resourceCulture);
            }
        }
    }
}
