ALTER TABLE [dbo].[DashboardYearlyLogins]
    ADD CONSTRAINT [PK_DashboardYearlyLogins] PRIMARY KEY CLUSTERED ([YearlyLoginId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

