ALTER TABLE [dbo].[DashboardMonthlyRegistrations]
    ADD CONSTRAINT [PK_DashboardMonthlyRegistrations] PRIMARY KEY CLUSTERED ([MonthlyRegistrationId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

