ALTER TABLE [dbo].[DashboardQuarterlyLogins]
    ADD CONSTRAINT [PK_DashboardQuarterlyLogins] PRIMARY KEY CLUSTERED ([QuarterlyLoginId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

