ALTER TABLE [dbo].[DashboardYearlyRegistrations]
    ADD CONSTRAINT [PK_DashboardYearlyRegistrations] PRIMARY KEY CLUSTERED ([YearlyRegistrationId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

