ALTER TABLE [dbo].[DashboardMonthlyLogins]
    ADD CONSTRAINT [PK_DashboardMonthlyLogins] PRIMARY KEY CLUSTERED ([MonthlyLoginId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

