ALTER TABLE [dbo].[DashboardDailyRegistrations]
    ADD CONSTRAINT [PK_DashboardDailyRegistrations] PRIMARY KEY CLUSTERED ([DailyRegistrationId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

