ALTER TABLE [dbo].[ProfileManagementProfiles]
    ADD CONSTRAINT [PK_ProfileManagementProfiles] PRIMARY KEY CLUSTERED ([ProfileId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

