#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.User.Authentication.Registration.FrontEnd.Views.Registration
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    using ThreeBytes.User.Authentication.Registration.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Registration/PartialRegister.cshtml")]
    public class PartialRegister : System.Web.Mvc.WebViewPage<ThreeBytes.User.Authentication.Registration.FrontEnd.Models.RegisterViewModel>
    {
        public PartialRegister()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div id=\"registation-form-container\">\r\n");


            
            #line 4 "..\..\Views\Registration\PartialRegister.cshtml"
     using (Html.BeginForm("Register", "Registration", FormMethod.Post, new { id = "registration-form", @class = "well" }))
    {

            
            #line default
            #line hidden
WriteLiteral("            <fieldset>\r\n\r\n                <h3><strong>New?</strong> Sign up</h3>\r" +
"\n                <hr />\r\n\r\n                <div class=\"clearfix\">\r\n             " +
"       <div class=\"input\">\r\n                        ");


            
            #line 13 "..\..\Views\Registration\PartialRegister.cshtml"
                   Write(Html.TextBoxFor(model => model.UserName, new { placeholder = "Username" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 14 "..\..\Views\Registration\PartialRegister.cshtml"
                         if (!ViewData.ModelState.IsValidField("UserName"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div class=\"alert alert-error\">\r\n                    " +
"            <a class=\"close\" data-dismiss=\"alert\">×</a>\r\n                       " +
"         ");


            
            #line 18 "..\..\Views\Registration\PartialRegister.cshtml"
                           Write(Html.ValidationMessageFor(model => model.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");


            
            #line 20 "..\..\Views\Registration\PartialRegister.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n\r\n                <div class=" +
"\"clearfix\">\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 26 "..\..\Views\Registration\PartialRegister.cshtml"
                   Write(Html.TextBoxFor(model => model.Email, new { placeholder = "Email" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 27 "..\..\Views\Registration\PartialRegister.cshtml"
                         if (!ViewData.ModelState.IsValidField("Email"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div class=\"alert alert-error\">\r\n                    " +
"            <a class=\"close\" data-dismiss=\"alert\">×</a>\r\n                       " +
"         ");


            
            #line 31 "..\..\Views\Registration\PartialRegister.cshtml"
                           Write(Html.ValidationMessageFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");


            
            #line 33 "..\..\Views\Registration\PartialRegister.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n\r\n                <div class=" +
"\"clearfix\">\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 39 "..\..\Views\Registration\PartialRegister.cshtml"
                   Write(Html.PasswordFor(model => model.Password, new { placeholder = "Password" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 40 "..\..\Views\Registration\PartialRegister.cshtml"
                         if (!ViewData.ModelState.IsValidField("Password"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div class=\"alert alert-error\">\r\n                    " +
"            <a class=\"close\" data-dismiss=\"alert\">×</a>\r\n                       " +
"         ");


            
            #line 44 "..\..\Views\Registration\PartialRegister.cshtml"
                           Write(Html.ValidationMessageFor(model => model.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");


            
            #line 46 "..\..\Views\Registration\PartialRegister.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n\r\n                <div class=" +
"\"clearfix\">\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 52 "..\..\Views\Registration\PartialRegister.cshtml"
                   Write(Html.PasswordFor(model => model.ConfirmPassword, new { placeholder = "Confirm Password" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <button class=\"btn btn-primary pull-right\" data-bind=\"c" +
"lick: register\">");


            
            #line 53 "..\..\Views\Registration\PartialRegister.cshtml"
                                                                                          Write(Resources.Register);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");


            
            #line 54 "..\..\Views\Registration\PartialRegister.cshtml"
                         if (!ViewData.ModelState.IsValidField("ConfirmPassword"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div class=\"alert alert-error\">\r\n                    " +
"            <a class=\"close\" data-dismiss=\"alert\">×</a>\r\n                       " +
"         ");


            
            #line 58 "..\..\Views\Registration\PartialRegister.cshtml"
                           Write(Html.ValidationMessageFor(model => model.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");


            
            #line 60 "..\..\Views\Registration\PartialRegister.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n            </fieldset>\r\n");


            
            #line 64 "..\..\Views\Registration\PartialRegister.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");


            
            #line 67 "..\..\Views\Registration\PartialRegister.cshtml"
 using (Html.BeginScriptContext())
{
    Html.AddScriptBlock(@"
    var registration = {};

    (function (index) {

        registration = index;

        index.register = function () {
            jQuery('#registration-form').submit();
        };

        jQuery(function () {
            ko.applyBindings(index, jQuery('#registation-form-container')[0]);
        });

    } (registration));");
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
