#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.User.Authentication.Registration.FrontEnd.Views.Registration
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    using ThreeBytes.User.Authentication.Registration.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Registration/VerifyAccount.cshtml")]
    public class VerifyAccount : System.Web.Mvc.WebViewPage<ThreeBytes.User.Authentication.Registration.FrontEnd.Models.VerifyAccountViewModel>
    {
        public VerifyAccount()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Views\Registration\VerifyAccount.cshtml"
  
    ViewBag.Title = Resources.BrowserTitleVerifyAccount;


            
            #line default
            #line hidden
WriteLiteral("\r\n<section id=\"account-verification\">\r\n    <div id=\"account-verification-containe" +
"r\" class=\"account-container\">\r\n        <div class=\"content clearfix\">\r\n");


            
            #line 10 "..\..\Views\Registration\VerifyAccount.cshtml"
             if (Model.Success)
            {

            
            #line default
            #line hidden
WriteLiteral("                <h2>");


            
            #line 12 "..\..\Views\Registration\VerifyAccount.cshtml"
               Write(Resources.SuccessfullyVerified);

            
            #line default
            #line hidden
WriteLiteral("</h2> \r\n");



WriteLiteral("                <p>");


            
            #line 13 "..\..\Views\Registration\VerifyAccount.cshtml"
              Write(Resources.YouAreNowAbleTo);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 13 "..\..\Views\Registration\VerifyAccount.cshtml"
                                         Write(Html.ActionLink(Resources.Login, "Login", "Login"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 14 "..\..\Views\Registration\VerifyAccount.cshtml"
            }
            else
            {
                using (Html.BeginForm("VerifyAccount", "Registration", FormMethod.Post, new { id = "verify-form" }))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <h1>Verify Account</h1>\r\n");



WriteLiteral("                    <div class=\"verify-fields\">\r\n                        <p>Verif" +
"y using your registered account:</p>\r\n                        <div class=\"field\"" +
">\r\n                            <label for=\"UserIdentifier\">");


            
            #line 23 "..\..\Views\Registration\VerifyAccount.cshtml"
                                                   Write(Resources.UserIdentifier);

            
            #line default
            #line hidden
WriteLiteral(":</label>\r\n                            <input type=\"text\" id=\"UserIdentifier\" nam" +
"e=\"UserIdentifier\" value=\"\" placeholder=\"User Identifier\" class=\"username-field\"" +
" />\r\n                        </div>\r\n");


            
            #line 26 "..\..\Views\Registration\VerifyAccount.cshtml"
                         if (!ViewData.ModelState.IsValidField("UserIdentifier"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div class=\"alert alert-error\">\r\n                    " +
"            <a class=\"close\" data-dismiss=\"alert\">×</a>\r\n                       " +
"         ");


            
            #line 30 "..\..\Views\Registration\VerifyAccount.cshtml"
                           Write(Html.ValidationMessageFor(model => model.UserIdentifier));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");


            
            #line 32 "..\..\Views\Registration\VerifyAccount.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"field\">\r\n                            <label" +
" for=\"VerifiedCode\">");


            
            #line 35 "..\..\Views\Registration\VerifyAccount.cshtml"
                                                 Write(Resources.VerifyCode);

            
            #line default
            #line hidden
WriteLiteral(":</label>\r\n                            <input type=\"text\" id=\"VerifiedCode\" name=" +
"\"VerifiedCode\" value=\"\" placeholder=\"Verify Code\" class=\"password-field\" />\r\n   " +
"                     </div>\r\n");


            
            #line 38 "..\..\Views\Registration\VerifyAccount.cshtml"
                         if (!ViewData.ModelState.IsValidField("VerifiedCode"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div class=\"alert alert-error\">\r\n                    " +
"            <a class=\"close\" data-dismiss=\"alert\">×</a>\r\n                       " +
"         ");


            
            #line 42 "..\..\Views\Registration\VerifyAccount.cshtml"
                           Write(Html.ValidationMessageFor(model => model.VerifiedCode));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");


            
            #line 44 "..\..\Views\Registration\VerifyAccount.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"login-actions\">\r\n                          " +
"  <button class=\"button btn btn-warning btn-large\" data-bind=\"click: verify\">");


            
            #line 47 "..\..\Views\Registration\VerifyAccount.cshtml"
                                                                                                  Write(Resources.Verify);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                        </div>\r\n                    </div>\r\n");


            
            #line 50 "..\..\Views\Registration\VerifyAccount.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</section>\r\n\r\n");


            
            #line 56 "..\..\Views\Registration\VerifyAccount.cshtml"
   if (!Model.Success)
   {
       using (Html.BeginScriptContext())
       {
           Html.AddScriptBlock(@"
        var verify_view_model = {};

        (function (index) {

            verify_view_model = index;

            index.verify = function () {
                jQuery('#verify-form').submit();
            };

            jQuery(function () {
                ko.applyBindings(index, jQuery('#account-verification-container')[0]);
            });

        } (verify_view_model));");
       }
   } 

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
