ALTER TABLE [dbo].[ExceptionView]
    ADD CONSTRAINT [PK_ExceptionView] PRIMARY KEY CLUSTERED ([ExceptionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

