#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBytes.Email.Dispatch.View.Frontend.Views.EmailDispatchView
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ThreeBytes.Core.Extensions.Mvc;
    using ThreeBytes.Email.Dispatch.View.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmailDispatchView/Details.cshtml")]
    public class Details : System.Web.Mvc.WebViewPage<ThreeBytes.Email.Dispatch.View.Entities.EmailDispatchViewEmailMessage>
    {
        public Details()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Views\EmailDispatchView\Details.cshtml"
  
    ViewBag.Title = Resources.BrowserTitle;


            
            #line default
            #line hidden
WriteLiteral(@"
<div id=""dispatched-email-details-container"">
    <div id=""dispatched-emails-details-modal"" class=""modal modal-medium-wide hide fade"">
        <div class=""modal-header"">
            <a href=""#"" class=""close"" data-bind=""click: raiseClose"">×</a>
            <h3>
                <span data-bind=""text: Subject""></span> ");


            
            #line 12 "..\..\Views\EmailDispatchView\Details.cshtml"
                                                   Write(Resources.Details);

            
            #line default
            #line hidden
WriteLiteral(@"
            </h3>
        </div>
        <div class=""modal-body modal-body-scrollable"">
            <div class=""row"">
                <div class=""span6"">    
                    <div class=""row"">
                        <div class=""span2"">
                            <div class=""display-label"">");


            
            #line 20 "..\..\Views\EmailDispatchView\Details.cshtml"
                                                  Write(Resources.From);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <div class=\"display-field\"><span data-bind=\"t" +
"ext: From\"></span></div>\r\n\r\n                            <div class=\"display-labe" +
"l\">");


            
            #line 23 "..\..\Views\EmailDispatchView\Details.cshtml"
                                                  Write(Resources.BCC);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <div class=\"display-field\"><span data-bind=\"t" +
"ext: BCC\"></span></div>\r\n                        </div>\r\n\r\n                     " +
"   <div class=\"span2\">\r\n                            <div class=\"display-label\">");


            
            #line 28 "..\..\Views\EmailDispatchView\Details.cshtml"
                                                  Write(Resources.To);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <div class=\"display-field\"><span data-bind=\"t" +
"ext: To\"></span></div>\r\n\r\n                            <div class=\"display-label\"" +
">");


            
            #line 31 "..\..\Views\EmailDispatchView\Details.cshtml"
                                                  Write(Resources.Html);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <div class=\"display-field\"><span data-bind=\"t" +
"ext: IsHtml\"></span></div>\r\n                        </div>\r\n\r\n                  " +
"      <div class=\"span2\">\r\n                            <div class=\"display-label" +
"\">");


            
            #line 36 "..\..\Views\EmailDispatchView\Details.cshtml"
                                                  Write(Resources.CC);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <div class=\"display-field\"><span data-bind=\"t" +
"ext: CC\"></span></div>\r\n\r\n                            <div class=\"display-label\"" +
">");


            
            #line 39 "..\..\Views\EmailDispatchView\Details.cshtml"
                                                  Write(Resources.Encoding);

            
            #line default
            #line hidden
WriteLiteral(@"</div>
                            <div class=""display-field""><span data-bind=""text: Encoding""></span></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class=""row"">
                <div class=""span6"">
                    <div class=""display-label"">");


            
            #line 47 "..\..\Views\EmailDispatchView\Details.cshtml"
                                          Write(Resources.Subject);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div class=\"display-field well\"><span data-bind=\"text" +
": Subject\"></span></div>\r\n\r\n                    <div class=\"display-label\">");


            
            #line 50 "..\..\Views\EmailDispatchView\Details.cshtml"
                                          Write(Resources.Body);

            
            #line default
            #line hidden
WriteLiteral(@"</div>
                    <div class=""display-field well""><span data-bind=""text: Body""></span></div>
                </div>
            </div>
        </div>
        <div class=""modal-footer"">
            <button class=""btn btn-danger"" data-bind=""click: raiseClose"">Close</button>
        </div>
    </div>
</div>

");


            
            #line 61 "..\..\Views\EmailDispatchView\Details.cshtml"
   
  using (Html.BeginScriptContext())
  {
    Html.AddScriptBlock(@"
    var dispatched_emails_details = {};

    (function (index) {

        dispatched_emails_details = index;

        index.Id = ko.observable();
        index.From = ko.observable();
        index.To = ko.observable();
        index.CC = ko.observable();
        index.BCC = ko.observable();
        index.Subject = ko.observable();
        index.Body = ko.observable();
        index.IsHtml = ko.observable();
        index.Encoding = ko.observable();

        index.raiseClose = function () {
            index.detailModal.modal('hide');
        };

        jQuery(document).bind('dispatchedEmailDetails', function (event, template) {

            jQuery.getJSON('" + @Url.Action("GetDetails", "Dispatch") + @"', { id: template.Id() }, function (data) {

                index.Id(data.Id);
                index.From(data.From);
                index.To(data.To);
                index.CC(data.CC);
                index.BCC(data.BCC);
                index.Subject(data.Subject);
                index.Body(data.Body);
                index.IsHtml(data.IsHtml);
                index.Encoding(data.Encoding);

                index.detailModal.modal('show');
            });
        });

        jQuery(function () {
            ko.applyBindings(index, jQuery('#dispatched-email-details-container')[0]);
            index.detailModal = jQuery('#dispatched-emails-details-modal').modal({ backdrop: true, closeOnEscape: true, modal: true, show: false });
        });
    } (dispatched_emails_details));");
  }

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
